# Use the official Java image as the base image
From azul/zulu-openjdk-centos:17-jre-latest

# Set the working directory to /app
WORKDIR /app
COPY marketdataservice.jar /app/marketdataservice.jar


# Run the jar file when the container starts
ENTRYPOINT ["java", "-jar", "/app/marketdataservice.jar"]
